<?php
define("MYSQL_USER", "");
define("MYSQL_PASSWORD", "");
define("MYSQL_DATABASE", "");
define("BOT_NAME", "");
define('BOT_TOKEN', '');
define('API_URL', 'https://api.telegram.org/bot' . BOT_TOKEN . '/');
define('PATH_TO_SITE', 'http://axeniabot.ru/');
define('ADMIN_IDS', '32512143,5492881');
define('NASH_CHAT_ID', '');
define('PATH_TO_WEBHOOK', '');
define('LOG_CHAT_ID', '');
define('TRASH_CHAT_ID', '');
define('DEFAULT_COOLDOWN', 0);
define('QIWI_PUBLIC_KEY', '');
define('QIWI_SECRET_KEY', '');
define('GOOGLE_API_KEY', '');
define('STRIPE_TOKEN', '');
define('BOT_PROXY', '');
define('BOT_PROXYPORT', '');
define('BOT_PROXYUSERNAME', '');
define('BOT_PROXYUSERPWD', '');